Added Action Hook Opcode and Screen Effects Global functionality
Bubb13/EEex pull request #55
Opened 2023-03-13 02:01 UTC by OlvynChuru

Note: For action hook functions, I switched the sprite and action parameters to match how they were in the old EEex (and also matching how other similar functions in EEex work; for Invoke Lua and Screen Effects, the sprite parameter comes last).

2023-03-16 22:54 UTC, Bubb13 requested changes

2023-03-16 22:54 UTC, Bubb13 commented on EEex/copy/EEex_Sprite.lua
> +EEex_SpellIDSType = {[1] = "SPPR", [2] = "SPWI", [3] = "SPIN", [4] = "SPCL"}
**Style:** Make local to `EEex_Sprite_GetSpellRES` or rename to `EEex_Sprite_Private_SpellIDSType`

2023-03-16 22:54 UTC, Bubb13 commented on EEex/copy/EEex_Sprite.lua
> +			return (EEex_SpellIDSType[math.floor(spellIDS / 1000)] .. spellIDS % 1000)
**Style:** `EEex_SpellIDSType`

2023-03-17 00:01 UTC, Bubb13 commented
I got the easy changes out of the way with [d999fb4](https://github.com/Bubb13/EEex/pull/55/commits/d999fb4f1fe98cd68f2d289295efda34288a4050), I'll wait until you weigh in on everything else. And, as always, thanks.

2023-04-01 19:16 UTC, OlvynChuru commented on EEex/copy/EEex_Action.lua
> +	EEex_Sprite_IterateEffects(sprite, function(effect)
Okay, so should I wait for you to implement that opcode? I'm not sure what else I'd do if you're not okay with this code.

2023-04-01 19:37 UTC, Bubb13 commented on EEex/copy/EEex_Action.lua
> +	EEex_Sprite_IterateEffects(sprite, function(effect)
Yeah, I'll try to implement it soon.

2023-04-09 21:21 UTC, Bubb13 commented on EEex/copy/EEex_Action.lua
> +	EEex_Sprite_IterateEffects(sprite, function(effect)
How does Bubb13/EEex@d6649697a740835196f2b8caf1fc8bce6e6c97d2 look? Op409, `param1 = 0` means listener is disabled, `param1 != 0` means listener is enabled. Resource is the indirect name of the function, which should be registered with `EEex_Action_AddEnabledSpriteStartedActionListener(funcName, func)`. When multiple effects target the same resource and sprite, the last one is used.

2023-04-13 19:40 UTC, closed without merging